import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
	api: [
		{
			type: "autogenerated",
			dirName: "api",
		},
	],
	guides: [
		{
			type: "autogenerated",
			dirName: "guides",
		},
	],
	tutorialSidebar: [
		"index",
		{
			type: "category",
			label: "API",
			items: ["api/authentication", "api/agents", "api/tasks", "api/events"],
		},
		{
			type: "category",
			label: "Guides",
			items: ["guides/getting-started", "guides/multi-agent-coordination", "guides/event-sourcing"],
		},
	],
};

export default sidebars;
